sudo: required
language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
install:
  - ./.travis.sh --install
  - pip install tox coveralls
script:
  - tox -v
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
